
import "./globals.css";
import Header from "./components/Header/Header.jsx";
import FooterWithWaves from "./components/FooterWithWaves/FooterWithWaves";

export const metadata = {
  title: "Bongo Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body> 
      <Header />      
        {children}
      <FooterWithWaves />
      
      </body>
      
    </html>
  );
}
 

